##default
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/defaulttest
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
#master
multiple:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mastertest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
#slave1multiple.datasource.slave
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/slavetest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml